baseURL: 'https://blog-qa.groupdocs.cloud/'
languageCode: 'en-us'
title: 'Document Automation REST APIs | GroupDocs Cloud'
theme: "PaperMod"
paginate: 10
enableRobotsTXT: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
        
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: GroupDocs Cloud
  description: ""
  keywords: [""]
  mainSections: # Add name of each folder under content folder that contains blog posts.
  - GroupDocs.Cloud # https://gohugo.io/functions/where/#mainsections 
  ShowShareButtons: true
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: true
  disableSpecial1stPost: true
  fuseOpts:
    keys: ["title"]

  label:
    text: "Home"
    #icon: /images/logo.png
    #iconHeight: 32
  
  assets:
    favicon: "/img/groupdocs.ico"
    favicon16x16:  "/img/groupdocs-16x16.png"
    favicon32x32:  "/img/groupdocs-32x32.png"
    apple_touch_icon:  "/img/groupdocs-apple-touch-icon.png"
    safari_pinned_tab:  "/img/groupdocs-safari-pinned-tab.svg"

  dynamicmenuid:
    en: aspose-en
    ja: aspose-ja
    ko: aspose-ko
    es: aspose-es
    de: aspose-de
    ru: aspose-ru
    fr: aspose-fr
    zh: aspose-zh
    it: aspose-it
    pt: aspose-pt
    ar: aspose-ar
    vi: aspose-vi
    zh-hant: aspose-zh-hant
    tr: aspose-tr
    id: aspose-id
    th: aspose-th
    fa: aspose-fa

# Disabled languages
disableLanguages: []
defaultContentLang: en

languages:
  en:
    languageName: English
    languageCode: en
    flag: flag-us
    weight: 1
  
  ja:
    languageName: 日本
    languageCode: ja
    flag: flag-jp
    weight: 2
    menu:
      main:
      - identifier: search
        name: 探す
        url: /ja/search/
        weight: 10
      - identifier: categories
        name: カテゴリ
        url: /categories/
        weight: 20
      - identifier: archive
        name: 記録
        url: /ja/archives/
        weight: 30
      - identifier: tags
        name: タグ
        url: /tags/
        weight: 40
  
  ko:
    languageName: 한국인
    languageCode: ko
    flag: flag-kr
    weight: 3
    menu:
      main:
      - identifier: search
        name: 검색
        url: /ko/search/
        weight: 10
      - identifier: categories
        name: 카테고리
        url: /categories/
        weight: 20
      - identifier: archive
        name: 보관소
        url: /ko/archives/
        weight: 30
      - identifier: tags
        name: 태그
        url: /tags/
        weight: 40
    
  es:
    languageName: Español
    languageCode: es
    flag: flag-es
    weight: 4
    menu:
      main:
      - identifier: search
        name: Búsqueda
        url: /es/search/
        weight: 10
      - identifier: categories
        name: Categorías
        url: /categories/
        weight: 20
      - identifier: archive
        name: Archivo
        url: /es/archives/
        weight: 30
      - identifier: tags
        name: Etiquetas
        url: /tags/
        weight: 40
  
  de:
    languageName: Deutsch
    languageCode: de
    flag: flag-de
    weight: 5
    menu:
      main:
      - identifier: search
        name: Suche
        url: /de/search/
        weight: 10
      - identifier: categories
        name: Kategorien
        url: /categories/
        weight: 20
      - identifier: archive
        name: Archiv
        url: /de/archives/
        weight: 30
      - identifier: tags
        name: Stichworte
        url: /tags/
        weight: 40
  
  ru:
    languageName: Русский
    languageCode: ru
    flag: flag-ru
    weight: 6
    menu:
      main:
      - identifier: search
        name: Поиск
        url: /ru/search/
        weight: 10
      - identifier: categories
        name: Категории
        url: /categories/
        weight: 20
      - identifier: archive
        name: Архив
        url: /ru/archives/
        weight: 30
      - identifier: tags
        name: Теги
        url: /tags/
        weight: 40
  
  fr:
    languageName: Français
    languageCode: fr
    flag: flag-fr
    weight: 7
    menu:
      main:
      - identifier: search
        name: Chercher
        url: /fr/search/
        weight: 10
      - identifier: categories
        name: Catégories
        url: /categories/
        weight: 20
      - identifier: archive
        name: Archiver
        url: /fr/archives/
        weight: 30
      - identifier: tags
        name: "Mots clés"
        url: /tags/
        weight: 40
  
  zh:
    languageName: 中文
    languageCode: zh
    flag: flag-cn
    weight: 8
    menu:
      main:
      - identifier: search
        name: 搜索
        url: /zh/search/
        weight: 10
      - identifier: categories
        name: 类别
        url: /categories/
        weight: 20
      - identifier: archive
        name: 档案
        url: /zh/archives/
        weight: 30
      - identifier: tags
        name: 标签
        url: /tags/
        weight: 40
  
  it:
    languageName: Italiano
    languageCode: it
    flag: flag-it
    weight: 9
    menu:
      main:
      - identifier: search
        name: Ricerca
        url: /it/search/
        weight: 10
      - identifier: categories
        name: Categorie
        url: /categories/
        weight: 20
      - identifier: archive
        name: Archivio
        url: /it/archives/
        weight: 30
      - identifier: tags
        name: Tag
        url: /tags/
        weight: 40
  
  pt:
    languageName: Português
    languageCode: pt
    flag: flag-pt
    weight: 10
    menu:
      main:
      - identifier: search
        name: Procurar
        url: /pt/search/
        weight: 10
      - identifier: categories
        name: Categorias
        url: /categories/
        weight: 20
      - identifier: archive
        name: Arquivo
        url: /pt/archives/
        weight: 30
      - identifier: tags
        name: Tag
        url: /tags/
        weight: 40
    
  ar:
    languageName: عربي
    languageCode: ar
    flag: flag-sa
    weight: 11
    menu:
      main:
      - identifier: search
        name: يبحث
        url: /ar/search/
        weight: 10
      - identifier: categories
        name: فئات
        url: /categories/
        weight: 20
      - identifier: archive
        name: أرشيف
        url: /ar/archives/
        weight: 30
      - identifier: tags
        name: العلامات
        url: /tags/
        weight: 40

  vi:
    languageName: Tiếng Việt
    languageCode: vi
    flag: flag-vn
    weight: 12
    menu:
      main:
      - identifier: search
        name: Tìm kiếm
        url: /vi/search/
        weight: 10
      - identifier: categories
        name: Thể loại
        url: /categories/
        weight: 20
      - identifier: archive
        name: lưu trữ
        url: /vi/archives/
        weight: 30
      - identifier: tags
        name: thẻ
        url: /tags/
        weight: 40

  zh-hant:
    languageName: 中國傳統的
    languageCode: zh-hant
    flag: flag-tw
    weight: 13
    menu:
      main:
      - identifier: search
        name: 搜索
        url: /zh-hant/search/
        weight: 10
      - identifier: categories
        name: 類別
        url: /categories/
        weight: 20
      - identifier: archive
        name: 檔案
        url: /zh-hant/archives/
        weight: 30
      - identifier: tags
        name: 標籤
        url: /tags/
        weight: 40
  tr:
    languageName: Türkçe
    languageCode: tr
    flag: flag-tr
    weight: 14
    menu:
      main:
      - identifier: search
        name: Arama
        url: /tr/search/
        weight: 10
      - identifier: categories
        name: Kategoriler
        url: /categories/
        weight: 20
      - identifier: archive
        name: Arşiv
        url: /tr/archives/
        weight: 30
      - identifier: tags
        name: Etiketler
        url: /tags/
        weight: 40
  id:
    languageName: Indonesian
    languageCode: id
    flag: flag-id
    weight: 15
    menu:
      main:
      - identifier: search
        name: Cari
        url: /id/search/
        weight: 10
      - identifier: categories
        name: Kategori
        url: /categories/
        weight: 20
      - identifier: archive
        name: Arsip
        url: /id/archives/
        weight: 30
      - identifier: tags
        name: Tag
        url: /tags/
        weight: 40
  th:
    languageName: Thai
    languageCode: th
    flag: flag-th
    weight: 16
    menu:
      main:
      - identifier: search
        name: ค้นหา
        url: /th/search/
        weight: 10
      - identifier: categories
        name: หมวดหมู่
        url: /categories/
        weight: 20
      - identifier: archive
        name: คลังเก็บเอกสารสำคัญ
        url: /th/archives/
        weight: 30
      - identifier: tags
        name: แท็ก
        url: /tags/
        weight: 40
  fa:
    languageName: فارسی
    languageCode: fa
    flag: flag-ir
    weight: 17
    menu:
      main:
      - identifier: search
        name: جستجو کردن
        url: /fa/search/
        weight: 10
      - identifier: categories
        name: دسته بندی ها
        url: /categories/
        weight: 20
      - identifier: archive
        name: بایگانی
        url: /fa/archives/
        weight: 30
      - identifier: tags
        name: برچسب ها
        url: /tags/
        weight: 40

permalinks:
  tags: /tag/:title/

menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 30
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 40

deployment:
  targets:
    name: "production"
    URL: "s3://blog-qa.groupdocs.cloud/?region=us-west-2"